name: Course Management Portal Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      #checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull the latest code
        run: |
          cd /home/node3/course-portal/frontend/course_management_portal_frontend
          git config --global --add safe.directory /home/node3/course-portal/frontend/course_management_portal_frontend
          git pull origin main

      - name: Deploy the containers
        run: |
          cd /home/node3/course-portal/frontend/course_management_portal_frontend
          docker-compose stop course-frontend || true
          docker system prune -af || true
          docker-compose up -d course-frontend
          docker ps

